### ISSUE TITLE
investigate if export was successful 

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/hca-ebi-dev-team#396]
Investigate if export of UCSC project uuid=2d846095-8a33-4f3c-97d4-585bafac13b4 has stalled - Export started Mar 12, 2021, 10:28:16 PM

and report outcome - https://embl-ebi-ait.slack.com/archives/C9XD6L0AD/p1615921101004400

**Comment by aaclan-ebi** [comment]
There's an assay experiment which failed to be processed.
``` 
2021-03-15 17:33:50,431  - exporter.terra.terra_listener - ERROR in terra_listener.py:119 _experiment_message_handler(): Failed to export experiment message with body: {"bundleUuid":"aadd2ec1-aec1-4347-
ab77-63dd94f98d8e","versionTimestamp":"2021-03-12T22:41:09.815Z","messageProtocol":null,"exportJobId":"604f9a7691708e06ec07128d","documentId":"604bee0591708e06ec06d1fc","documentUuid":"aadd2ec1-aec1-4347
 2021-03-15 17:33:50,432  - exporter.terra.terra_listener - ERROR in terra_listener.py:120 _experiment_message_handler(): [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/app/exporter/terra/terra_listener.py", line 107, in _experiment_message_handler
    self.terra_exporter.export(exp.process_uuid, exp.submission_uuid, exp.experiment_uuid, exp.experiment_version, exp.job_id)
  File "/app/exporter/terra/terra_exporter.py", line 24, in export
    self.dcp_staging_client.transfer_data_files(submission, project.uuid, export_job_id)
  File "/app/exporter/terra/dcp_staging_client.py", line 67, in transfer_data_files
    self.gcs_xfer.transfer_upload_area(bucket_and_key[0], bucket_and_key[1], project_uuid, export_job_id)
  File "/app/exporter/terra/gcs.py", line 90, in transfer_upload_area
    maybe_existing_job = self.get_job(transfer_job.name)
  File "/app/exporter/terra/gcs.py", line 116, in get_job
    return self._get_job(job_name, two_seconds, 0, two_minutes_in_seconds)
  File "/app/exporter/terra/gcs.py", line 124, in _get_job
    projectId=self.project_id).execute()
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 909, in execute
    headers=self.headers,
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 204, in _retry_request
    raise exception
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 177, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/google_auth_httplib2.py", line 190, in request
    self._request, method, uri, request_headers)
  File "/usr/local/lib/python3.7/site-packages/google/auth/credentials.py", line 133, in before_request
    self.refresh(request)
  File "/usr/local/lib/python3.7/site-packages/google/oauth2/service_account.py", line 361, in refresh
    access_token, expiry, _ = _client.jwt_grant(request, self._token_uri, assertion)
  File "/usr/local/lib/python3.7/site-packages/google/oauth2/_client.py", line 153, in jwt_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/usr/local/lib/python3.7/site-packages/google/oauth2/_client.py", line 105, in _token_endpoint_request
    response = request(method="POST", url=token_uri, headers=headers, body=body)
  File "/usr/local/lib/python3.7/site-packages/google_auth_httplib2.py", line 117, in __call__
    url, method=method, body=body, headers=headers, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1994, in request
    cachekey,
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1651, in _request
    conn, request_uri, method, body, headers
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1558, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1032, in _send_output
:
```

I redeployed the exporter in prod to retry it and it worked. The submission status is now Exported.

**Comment by lauraclarke** [comment]
Parisa has flagged this as exported to the TDR import team so I have moved this to done
