### ISSUE TITLE
Project SurveyhumanBrainTranscriptomediversity stuck in Exporting in prod

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#411]
Reported on Slack by Rachel Schwartz https://embl-ebi-ait.slack.com/archives/C9XD6L0AD/p1619026678140300?thread_ts=1618955401.140000&cid=C9XD6L0AD

shortname: SurveyhumanBrainTranscriptomediversity
Project uuid: 52b29aa4-c8d6-42b4-807a-b35be94469ca
https://contribute.data.humancellatlas.org/projects/detail?uuid=52b29aa4-c8d6-42b4-807a-b35be94469ca

**Comment by aaclan-ebi** [comment]
There were 20 experiments which failed with the following error:

```
 2021-04-20 21:54:08,769  - exporter.terra.terra_listener - ERROR in terra_listener.py:119 _experiment_message_handler(): Failed to export experiment message with body: {"bundleUuid":"5ff9e768-0433-4aaf-b4c4-a75c5cfb2925","versionTimestamp":"2021-04-20T20:39:52.686Z","messageProtocol":null,"exportJobId":"607f4c7add9aab1232d2fba9","documentId":"607f3c18dd9aab1232d2fb0c","documentUuid":"5ff9e768-0433-4aaf-b4c4-a75c5cfb2925","callbackLink":"/processes/607f3c18dd9aab1232d2fb0c","documentType":"Process","envelopeId":"607f3bb6dd9aab1232d2f258","envelopeUuid":"7f59a253-28d9-4c1f-a2f3-01ca454a55f0","index":309,"total":466}
 2021-04-20 21:54:08,769  - exporter.terra.terra_listener - ERROR in terra_listener.py:120 _experiment_message_handler(): <HttpError 429 when requesting https://storagetransfer.googleapis.com/v1/transferOperations?filter=%7B%22project_id%22%3A+%22mystical-slate-284720%22%2C+%22job_names%22%3A+%5B%22transferJobs%2F607f4c7add9aab1232d2fba9%22%5D%7D&alt=json returned "Quota exceeded for quota metric 'Read requests (list/get)' and limit 'Read requests (list/get) per minute per user' of service 'storagetransfer.googleapis.com' for consumer 'project_number:612961917858'.". Details: "[{'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'RATE_LIMIT_EXCEEDED', 'domain': 'googleapis.com', 'metadata': {'service': 'storagetransfer.googleapis.com', 'quota_limit': 'ReadOnlyRequestsPerMinutePerUser', 'quota_metric': 'storagetransfer.googleapis.com/read_only_requests', 'consumer': 'projects/612961917858'}}]">
Traceback (most recent call last):
  File "/app/exporter/terra/terra_listener.py", line 107, in _experiment_message_handler
    self.terra_exporter.export(exp.process_uuid, exp.submission_uuid, exp.experiment_uuid, exp.experiment_version, exp.job_id)
  File "/app/exporter/terra/terra_exporter.py", line 35, in export
    self.dcp_staging_client.transfer_data_files(submission, project.uuid, export_job_id)
  File "/app/exporter/terra/dcp_staging_client.py", line 67, in transfer_data_files
    self.gcs_xfer.transfer_upload_area(bucket_and_key[0], bucket_and_key[1], project_uuid, export_job_id)
  File "/app/exporter/terra/gcs.py", line 92, in transfer_upload_area
    self.assert_job_complete(transfer_job.name)
  File "/app/exporter/terra/gcs.py", line 140, in assert_job_complete
    return self._assert_job_complete(job_name, wait_time_seconds, time_waited_seconds, max_wait_time_seconds)
  File "/app/exporter/terra/gcs.py", line 151, in _assert_job_complete
    response: Dict = request.execute()
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 935, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 429 when requesting https://storagetransfer.googleapis.com/v1/transferOperations?filter=%7B%22project_id%22%3A+%22mystical-slate-284720%22%2C+%22job_names%22%3A+%5B%22transferJobs%2F607f4c7add9aab1232d2fba9%22%5D%7D&alt=json returned "Quota exceeded for quota metric 'Read requests (list/get)' and limit 'Read requests (list/get) per minute per user' of service 'storagetransfer.googleapis.com' for consumer 'project_number:612961917858'.". Details: "[{'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'RATE_LIMIT_EXCEEDED', 'domain': 'googleapis.com', 'metadata': {'service': 'storagetransfer.googleapis.com', 'quota_limit': 'ReadOnlyRequestsPerMinutePerUser', 'quota_metric': 'storagetransfer.googleapis.com/read_only_requests', 'consumer': 'projects/612961917858'}}]">
----- ingest-exporter-5449d69c87-wt4hr (previous)
----- ingest-exporter-5449d69c87-wt4hr
 2021-04-15 15:15:31,435  - ingest.api.ingestapi - INFO in ingestapi.py:30 __init__(): using http://172.20.134.175:80 for ingest API
 2021-04-15 15:15:32,241  - manifest.receiver.ManifestReceiver - INFO in receiver.py:18 run(): Running ManifestReceiver
 2021-04-15 15:15:32,265  - ingest.api.ingestapi - INFO in ingestapi.py:30 __init__(): using http://172.20.134.175:80 for ingest API
 2021-04-15 15:15:33,598  - exporter.terra.terra_listener - INFO in terra_listener.py:106 _experiment_message_handler(): Received experiment message for process ea07e88d-74e7-4a38-b53b-46e0e00bdb83 (index 174 for submission da17a2ee-dab3-4a0f-93fb-7b82fd9b8a4f)
```

We seem to be getting a lot of RATE_LIMIT_EXCEEDED. I'll file a ticket on the prod dev to fix this.

**Comment by aaclan-ebi** [comment]
The submission is now complete.
