### ISSUE TITLE
CervicalCancerLandscape and CorticalNephrogenicNicheKidney are stuck in export

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#429]
CervicalCancerLandscape:
https://contribute.data.humancellatlas.org/submissions/detail?uuid=3864f954-4707-42d7-8782-735a8b6c83a4&project=d012d476-8f8c-4ff3-89d6-ebbe22c1b5c1

CorticalNephrogenicNicheKidney:
https://contribute.data.humancellatlas.org/submissions/detail?uuid=51bc39b1-2347-4307-800e-85615b278314&project=71436067-ac41-4ace-be1b-2fbcc2cb02fa

**Comment by aaclan-ebi** [comment]
Found 2 messages which failed in logs:
```
12:05 $ cat ingest-exporter_2021-06-23T17\:18\:23.000Z.log | grep "Failed to export"
ingest-exporter-5dfc7d997b-72n92 :   2021-06-21 20:53:14,911  - exporter.terra.terra_listener - ERROR in terra_listener.py:88 _experiment_message_handler(): Failed to export experiment message with body: {"exportJobId":"60d0fc34e259f07661264018","documentId":"60d0f0cee259f07661264015","documentUuid":"010ca98d-e74e-43a6-a8b6-a3ff72ba02a9","callbackLink":"/processes/60d0f0cee259f07661264015","documentType":"process","envelopeId":"60d0f0c6e259f07661263ff2","envelopeUuid":"3864f954-4707-42d7-8782-735a8b6c83a4","projectId":"60d0f0cde259f07661263ff4","projectUuid":"d012d476-8f8c-4ff3-89d6-ebbe22c1b5c1","index":7,"total":8}
ingest-exporter-5dfc7d997b-krwpz :   2021-06-21 15:50:33,643  - exporter.terra.terra_listener - ERROR in terra_listener.py:88 _experiment_message_handler(): Failed to export experiment message with body: {"exportJobId":"60d0b542e259f07661263847","documentId":"60cbde7be259f07661262d84","documentUuid":"9376519f-89c7-470b-a076-88cf06cdd172","callbackLink":"/processes/60cbde7be259f07661262d84","documentType":"process","envelopeId":"60cbde74e259f07661262d6d","envelopeUuid":"51bc39b1-2347-4307-800e-85615b278314","projectId":"60cbde7be259f07661262d6f","projectUuid":"71436067-ac41-4ace-be1b-2fbcc2cb02fa","index":2,"total":4}
✔ ~/dev/ait/repos/ingest-kube-deployment [maste
```

**Comment by aaclan-ebi** [comment]
Both encountered similar errors:

```
ent_message_handler(): [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/app/exporter/terra/terra_listener.py", line 76, in _experiment_message_handler
    self.terra_exporter.export(exp.process_uuid, exp.submission_uuid, exp.job_id)
  File "/app/exporter/terra/terra_exporter.py", line 37, in export
    transfer_job_spec, success = self.dcp_staging_client.transfer_data_files(submission, project.uuid, export_job_id)
  File "/app/exporter/terra/dcp_staging_client.py", line 67, in transfer_data_files
    transfer_job_spec, success = self.gcs_xfer.transfer_upload_area(bucket_and_key[0], bucket_and_key[1], project_uuid, export_job_id)
  File "/app/exporter/terra/gcs.py", line 89, in transfer_upload_area
    self.client.transferJobs().create(body=transfer_job_spec.to_dict()).execute()
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 929, in execute
    headers=self.headers,
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 222, in _retry_request
    raise exception
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 191, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/google_auth_httplib2.py", line 225, in request
    **kwargs
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1709, in request
    conn, authority, uri, request_uri, method, body, headers, redirections, cachekey,
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1424, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1347, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1032, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 993, in send
    self.sock.sendall(data)
  File "/usr/local/lib/python3.7/ssl.py", line 1034, in sendall
    v = self.send(byte_view[count:])
  File "/usr/local/lib/python3.7/ssl.py", line 1003, in send
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe
```



```
2021-06-21 20:53:14,911  - exporter.terra.terra_listener - ERROR in terra_listener.py:88 _experiment_message_handler(): Failed to export experiment message with body: {"exportJobId":"60d0fc34e259f07661264018","documentId":"60d0f0cee259f07661264015","documentUuid":"010ca98d-e74e-43a6-a8b6-a3ff72ba02a9","callbackLink":"/processes/60d0f0cee259f07661264015","documentType":"process","envelopeId":"60d0f0c6e259f07661263ff2","envelopeUuid":"3864f954-4707-42d7-8782-735a8b6c83a4","projectId":"60d0f0cde259f07661263ff4","projectUuid":"d012d476-8f8c-4ff3-89d6-ebbe22c1b5c1","index":7,"total":8}
 2021-06-21 20:53:14,911  - exporter.terra.terra_listener - ERROR in terra_listener.py:89 _experiment_message_handler(): [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/app/exporter/terra/terra_listener.py", line 76, in _experiment_message_handler
    self.terra_exporter.export(exp.process_uuid, exp.submission_uuid, exp.job_id)
  File "/app/exporter/terra/terra_exporter.py", line 37, in export
    transfer_job_spec, success = self.dcp_staging_client.transfer_data_files(submission, project.uuid, export_job_id)
  File "/app/exporter/terra/dcp_staging_client.py", line 67, in transfer_data_files
    transfer_job_spec, success = self.gcs_xfer.transfer_upload_area(bucket_and_key[0], bucket_and_key[1], project_uuid, export_job_id)
  File "/app/exporter/terra/gcs.py", line 89, in transfer_upload_area
    self.client.transferJobs().create(body=transfer_job_spec.to_dict()).execute()
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 929, in execute
    headers=self.headers,
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 222, in _retry_request
    raise exception
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 191, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/google_auth_httplib2.py", line 225, in request
    **kwargs
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1709, in request
    conn, authority, uri, request_uri, method, body, headers, redirections, cachekey,
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1424, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1347, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1032, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 993, in send
    self.sock.sendall(data)
  File "/usr/local/lib/python3.7/ssl.py", line 1034, in sendall
    v = self.send(byte_view[count:])
  File "/usr/local/lib/python3.7/ssl.py", line 1003, in send
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by aaclan-ebi** [comment]
retried by deleting the failed pods:

```
$ kubectl delete pod ingest-exporter-5dfc7d997b-72n92
$ kubectl delete pod ingest-exporter-5dfc7d997b-krwpz
```

Both submissions are now complete.
