### ISSUE TITLE
Validator suddenly stops consuming messages

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#74]
Some submissions were deleted and caused the validator to fail and stops consuming messages. When this is fixed deleting a submission whilst it is being validated will no longer be an issue.

**Comment by aaclan-ebi** [comment]
```
Unhandled rejection StatusCodeError: 404 - undefined
    at new StatusCodeError (/app/node_modules/request-promise/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/app/node_modules/request-promise/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/app/node_modules/request-promise/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/app/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/app/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
Unhandled rejection StatusCodeError: 404 - undefined
    at new StatusCodeError (/app/node_modules/request-promise/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/app/node_modules/request-promise/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/app/node_modules/request-promise/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/app/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/app/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
Unhandled rejection StatusCodeError: 404 - undefined
    at new StatusCodeError (/app/node_modules/request-promise/node_modules/request-promise-core/lib/errors.js:32:15)```
